<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('games')->insert(
            [
                [
                    'id' => 1,
                    'game_image' => "https://pcgames9505.weebly.com/uploads/1/0/2/1/102119388/nfs2secover_1_orig.jpg",
                    'name' => "NEED FOR SPEED II: SE",
                    'description' => "Run fast like the wind.",
                    'score' => 8.3,
                    'genre' => "Racing",
                    'publisher' => "Electronic Arts",
                    'release_date' => "1997-10-10",
                ],
                [
                    'id' => 2,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/13/houseofthedead-1652475192188.jpg?width=300&crop=1%3A1%2Csmart&dpr=2",
                    'name' => "THE HOUSE OF THE DEAD",
                    'description' => "Keep shooting until you run out of ammo.",
                    'score' => 9.2,
                    'genre' => "Action",
                    'publisher' => "Sega",
                    'release_date' => "1998-01-06",
                ],
                [
                    'id' => 3,
                    'game_image' => "https://i.3djuegos.com/juegos/8454/dungeon_master/fotos/ficha/dungeon_master-1916276.webp",
                    'name' => "DUNGEON MASTER",
                    'description' => "Dungeon Master is an epic RPG masterpiece that revolutionizes and rejuvenates the genre.",
                    'score' => 7.1,
                    'genre' => "RPG",
                    'publisher' => "FTL Games",
                    'release_date' => "1992-06-04",
                ],
                [
                    'id' => 4,
                    'game_image' => "https://cdn.wikimg.net/en/strategywiki/images/b/b1/PoP2_cover.jpg",
                    'name' => "PRINCE OF PERSIA 2: THE SHADOW & THE FLAME",
                    'description' => "It's an action game, set in a platform, middle east and puzzle elements themes",
                    'score' => 6,
                    'genre' => "Action",
                    'publisher' => "Broderbund Software",
                    'release_date' => "1993-05-05",
                ],
                [
                    'id' => 5,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/04/16/pacman-1650079973919.jpg?width=300&crop=1%3A1%2Csmart&dpr=2",
                    'name' => "PAC-MAN",
                    'description' => "Pacman is Pacman",
                    'score' => 10.01,
                    'genre' => "Action",
                    'publisher' => "Atarisoft",
                    'release_date' => "1983-07-19",
                ],
                [
                    'id' => 6,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/12/22/incrediblemachine-1671734851893.jpg?width=300&crop=1%3A1%2Csmart&dpr=2",
                    'name' => "THE INCREDIBLE MACHINE",
                    'description' => "One can say this series is the precursor to all the puzzle solving video games existing today.",
                    'score' => 4.8,
                    'genre' => "Puzzle",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1994-04-04",
                ],
                [
                    'id' => 7,
                    'game_image' => "https://www.belgianchesshistory.be/wp-content/uploads/2018/02/Sargon-II.jpg",
                    'name' => "SARGON II",
                    'description' => "this strategy game is abandonware and is set in a board / party game, chess and turn-based themes.",
                    'score' => 7.8,
                    'genre' => "Strategy",
                    'publisher' => "Green Valley Publishing",
                    'release_date' => "1983-04-02",
                ],         
                [
                    'id' => 8,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/06/doom-1993-id-1638823790037.png?width=300&crop=1%3A1%2Csmart",
                    'name' => "Doom",
                    'description' => "A first-person shooter game in which the player must fight their way through hordes of demons and undead creatures to survive and save humanity.",
                    'score' => 9.0,
                    'genre' => "FPS",
                    'publisher' => "id Software",
                    'release_date' => "1993-12-10",
                ],
                [
                    'id' => 9 ,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/09/simcity2000-1639016420666.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "SimCity 2000",
                    'description' => "A city-building simulation game in which the player acts as the mayor of a city, managing its growth and development through various challenges and obstacles.",
                    'score' => 8.5,
                    'genre' => "City-building simulation",
                    'publisher' => "Maxis",
                    'release_date' => "1993-06-01",
                ],
                [
                    'id' => 10,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/14/princeofpersia-sq-1644880806695.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Prince of Persia",
                    'description' => "An action-adventure platformer game in which the player controls the Prince as he navigates through a series of perilous levels to rescue the Princess.",
                    'score' => 8.0,
                    'genre' => "Action-adventure, platformer",
                    'publisher' => "Brøderbund",
                    'release_date' => "1989-10-03",
                ],
                [
                    'id' => 11,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/04/01/xwing-1648856399676.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Star Wars: X-Wing",
                    'description' => "A space simulation game in which the player pilots an X-wing starfighter for the Rebel Alliance, engaging in dogfights and completing various missions.",
                    'score' => 9.0,
                    'genre' => "Space simulation",
                    'publisher' => "LucasArts",
                    'release_date' => "1993-01-01",
                ],
                [
                    'id' => 12,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/09/monkeyisland2-1639016626307.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Monkey Island 2: LeChuck's Revenge",
                    'description' => "An adventure game in which the player controls Guybrush Threepwood, a pirate in search of the legendary treasure of Big Whoop, while also dealing with the ghost pirate LeChuck.",
                    'score' => 9.5,
                    'genre' => "Adventure",
                    'publisher' => "LucasArts",
                    'release_date' => "19911-12-01",
                ],
                [
                    'id' => 13,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/30/ultima7-1648674172163.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Ultima VII: The Black Gate",
                    'description' => "A role-playing game in which the player takes on the role of the Avatar, a hero on a quest to stop a cult from summoning a powerful demon.",
                    'score' => 8.5,
                    'genre' => "Role-playing",
                    'publisher' => "Origin Systems",
                    'release_date' => "1992-04-16",
                ],
                [
                    'id' => 14,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/diablo1-sq-1643999156851.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Diablo",
                    'description' => "An action role-playing game in which the player must explore a dungeon beneath the town of Tristram, battling various monsters and the demon Diablo himself.",
                    'score' => 9.0,
                    'genre' => "Action role-playing",
                    'publisher' => "Blizzard Entertainment",
                    'release_date' => "1996-12-31",
                ],
                [
                    'id' => 15,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/13/daggerfall-es-sq-1642032706144.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "The Elder Scrolls II: Daggerfall",
                    'description' => "A role-playing game in which the player explores a vast open world, completing quests and battling monsters to uncover the truth behind a sinister conspiracy.",
                    'score' => 8.0,
                    'genre' => "Role-playing",
                    'publisher' => "Bethesda Softworks",
                    'release_date' => "1996-08-31",
                ],         
                [
                    'id' => 16,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/syndicate-sq-1644001563752.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Syndicate",
                    'description' => "A real-time tactics game in which the player controls a team of cyborg agents, completing missions and battling rival syndicates in a dystopian future.",
                    'score' => 8.5,
                    'genre' => "RTS",
                    'publisher' => "Bullfrog Productions",
                    'release_date' => "1993-06-06",
                ],  
                [
                    'id' => 17,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/aloneinthedark-sq2-1644001153398.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Alone in the Dark",
                    'description' => "A survival horror game in which the player must solve puzzles and fight off supernatural enemies to escape a haunted mansion.",
                    'score' => 7.9,
                    'genre' => "Survival horror",
                    'publisher' => "Infogrames",
                    'release_date' => "1992-06-01",
                ],
                [
                    'id' => 18,
                    'game_image' => "https://cdn.cdkeys.com/700x700/media/catalog/product/f/1/f117a_nighthawk_stealth_fighter_2.0_pc.jpg",
                    'name' => "F-117A Nighthawk Stealth Fighter 2.0",
                    'description' => "A combat flight simulation game in which the player pilots the F-117A Nighthawk stealth fighter and engages in various missions.",
                    'score' => 7.2,
                    'genre' => "Flight simulation",
                    'publisher' => "MicroProse",
                    'release_date' => "1991-12-31",
                ],
                [
                    'id' => 19,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/24/wolfenstein-3d-button-1643068723102.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Wolfenstein 3D",
                    'description' => "A first-person shooter game in which the player must escape from a Nazi prison and defeat the evil regime.",
                    'score' => 8.3,
                    'genre' => "FPS",
                    'publisher' => "id Software",
                    'release_date' => "1992-05-05",
                ],
                [
                    'id' => 20,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/12/21/loungelizards-1671607111772.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Leisure Suit Larry 1: In the Land of the Lounge Lizards",
                    'description' => "A comedic adventure game in which the player must help the protagonist Larry Laffer find love and navigate the seedy underbelly of the city.",
                    'score' => 6.7,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1987-05-05",
                ],
                [
                    'id' => 21,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/14/myst-1652553321305.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Myst",
                    'description' => "An adventure game in which the player explores a mysterious island, solving puzzles and uncovering the secrets of the island's past.",
                    'score' => 9.0,
                    'genre' => "Adventure",
                    'publisher' => "Broderbund",
                    'release_date' => "1993-09-24",
                ],
                [
                    'id' => 22,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/30/uunderworlds-1648680562969.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Ultima Underworld: The Stygian Abyss",
                    'description' => "A first-person action RPG game in which the player explores the Stygian Abyss, battling foes and completing quests to save the world from destruction.",
                    'score' => 8.5,
                    'genre' => "RPG",
                    'publisher' => "Origin Systems",
                    'release_date' => "1992-03-23",
                ],
                [
                    'id' => 22,
                    'game_image' => "https://miabandonaware.com/wp-content/uploads/2017/11/BattleChess.jpg",
                    'name' => "Battle Chess",
                    'description' => "A chess game in which the pieces come to life and battle it out on the board in animated sequences.",
                    'score' => 7.5,
                    'genre' => "Board game",
                    'publisher' => "Interplay Productions",
                    'release_date' => "1988-12-31",
                ],         
                [
                    'id' => 23,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/12/sidmeiersciv-sq-1641950900839.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Civilization",
                    'description' => "A strategy game in which the player guides a civilization from ancient times to the modern era, managing resources, building infrastructure, and waging war against other civilizations.",
                    'score' => 9.5,
                    'genre' => "Strategy",
                    'publisher' => "MicroProse",
                    'release_date' => "1991-09-01",
                ],  
                [
                    'id' => 24,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/17/commanderkeen-sq-1645060606759.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Commander Keen",
                    'description' => "A platformer game in which the player controls a young boy named Billy Blaze who travels to alien planets to stop an evil alien race from destroying Earth.",
                    'score' => 8.5,
                    'genre' => "Platformer",
                    'publisher' => "id Software",
                    'release_date' => "1990-12-14",
                ],
                [
                    'id' => 25,
                    'game_image' => "https://pcmedia.ign.com/pc/image/object/006/006765/688985boxart_160w.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Quest for Glory: So You Want to Be a Hero",
                    'description' => "A hybrid adventure and RPG game in which the player creates a character and embarks on a quest to become a hero, completing quests and battling monsters along the way.",
                    'score' => 8.9,
                    'genre' => "Adventure/RPG",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1989-10-01",
                ],
                [
                    'id' => 26,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/systemshock-sq4-1644000955813.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "System Shock",
                    'description' => "A first-person action RPG game in which the player explores a space station and battles rogue AI and mutants to uncover the truth behind a sinister conspiracy.",
                    'score' => 9.0,
                    'genre' => "RPG",
                    'publisher' => "Looking Glass Technologies",
                    'release_date' => "1994-09-22",
                ],
                [
                    'id' => 27,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/03/24/simant-1679696128032.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "SimAnt",
                    'description' => "A simulation game in which the player controls an ant colony, managing resources, battling other insects, and expanding the colony's territory.",
                    'score' => 7.8,
                    'genre' => "Simulation",
                    'publisher' => "Maxis",
                    'release_date' => "1991-12-31",
                ],
                [
                    'id' => 28,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/09/larry3-1652056361433.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Leisure Suit Larry 3: Passionate Patti in Pursuit of the Pulsating Pectorals",
                    'description' => "A comedic adventure game in which the player takes on the role of Patti, a friend of Larry's, who is on a quest to find a missing rock star and uncover a sinister plot.",
                    'score' => 7.1,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1989-11-01",
                ],
                [
                    'id' => 29,
                    'game_image' => "https://pcmedia.ign.com/pc/image/object/008/008649/StarControl2_PCBOX.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Star Control II",
                    'description' => "A space exploration and combat game in which the player commands a spaceship and travels the galaxy, interacting with alien races, gathering resources, and battling enemy ships.",
                    'score' => 9.3,
                    'genre' => "Action/Strategy",
                    'publisher' => "Accolade",
                    'release_date' => "1992-11-30",
                ],
                [
                    'id' => 30,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/indyfateofatlantis-sq-1644002663775.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Indiana Jones and the Fate of Atlantis",
                    'description' => "An adventure game in which the player controls Indiana Jones and sets out to find the lost city of Atlantis, using archaeological skills and combat tactics to overcome obstacles.",
                    'score' => 8.8,
                    'genre' => "Adventure",
                    'publisher' => "LucasArts",
                    'release_date' => "1992-06-01",
                ],         
            ]
        );
    }
}
