<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('games')->insert(
            [
                [
                    'id' => 1,
                    'game_image' => "https://pcgames9505.weebly.com/uploads/1/0/2/1/102119388/nfs2secover_1_orig.jpg",
                    'name' => "NEED FOR SPEED II: SE",
                    'description' => "Run fast like the wind.",
                    'score' => 8.3,
                    'genre' => "Racing",
                    'publisher' => "Electronic Arts",
                    'release_date' => "1997-10-10",
                ],
                [
                    'id' => 2,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/13/houseofthedead-1652475192188.jpg?width=300&crop=1%3A1%2Csmart&dpr=2",
                    'name' => "THE HOUSE OF THE DEAD",
                    'description' => "Keep shooting until you run out of ammo.",
                    'score' => 9.2,
                    'genre' => "Action",
                    'publisher' => "Sega",
                    'release_date' => "1998-01-06",
                ],
                [
                    'id' => 3,
                    'game_image' => "https://i.3djuegos.com/juegos/8454/dungeon_master/fotos/ficha/dungeon_master-1916276.webp",
                    'name' => "DUNGEON MASTER",
                    'description' => "Dungeon Master is an epic RPG masterpiece that revolutionizes and rejuvenates the genre.",
                    'score' => 7.1,
                    'genre' => "RPG",
                    'publisher' => "FTL Games",
                    'release_date' => "1992-06-04",
                ],
                [
                    'id' => 4,
                    'game_image' => "https://cdn.wikimg.net/en/strategywiki/images/b/b1/PoP2_cover.jpg",
                    'name' => "PRINCE OF PERSIA 2: THE SHADOW & THE FLAME",
                    'description' => "It's an action game, set in a platform, middle east and puzzle elements themes",
                    'score' => 6,
                    'genre' => "Action",
                    'publisher' => "Broderbund Software",
                    'release_date' => "1993-05-05",
                ],
                [
                    'id' => 5,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/04/16/pacman-1650079973919.jpg?width=300&crop=1%3A1%2Csmart&dpr=2",
                    'name' => "PAC-MAN",
                    'description' => "Pacman is Pacman",
                    'score' => 10.01,
                    'genre' => "Action",
                    'publisher' => "Atarisoft",
                    'release_date' => "1983-07-19",
                ],
                [
                    'id' => 6,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/12/22/incrediblemachine-1671734851893.jpg?width=300&crop=1%3A1%2Csmart&dpr=2",
                    'name' => "THE INCREDIBLE MACHINE",
                    'description' => "One can say this series is the precursor to all the puzzle solving video games existing today.",
                    'score' => 4.8,
                    'genre' => "Puzzle",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1994-04-04",
                ],
                [
                    'id' => 7,
                    'game_image' => "https://www.belgianchesshistory.be/wp-content/uploads/2018/02/Sargon-II.jpg",
                    'name' => "SARGON II",
                    'description' => "this strategy game is abandonware and is set in a board / party game, chess and turn-based themes.",
                    'score' => 7.8,
                    'genre' => "Strategy",
                    'publisher' => "Green Valley Publishing",
                    'release_date' => "1983-04-02",
                ],
                [
                    'id' => 8,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/06/doom-1993-id-1638823790037.png?width=300&crop=1%3A1%2Csmart",
                    'name' => "Doom",
                    'description' => "A first-person shooter game in which the player must fight their way through hordes of demons and undead creatures to survive and save humanity.",
                    'score' => 9.0,
                    'genre' => "FPS",
                    'publisher' => "id Software",
                    'release_date' => "1993-12-10",
                ],
                [
                    'id' => 9,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/09/simcity2000-1639016420666.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "SimCity 2000",
                    'description' => "A city-building simulation game in which the player acts as the mayor of a city, managing its growth and development through various challenges and obstacles.",
                    'score' => 8.5,
                    'genre' => "City-building simulation",
                    'publisher' => "Maxis",
                    'release_date' => "1993-06-01",
                ],
                [
                    'id' => 10,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/14/princeofpersia-sq-1644880806695.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Prince of Persia",
                    'description' => "An action-adventure platformer game in which the player controls the Prince as he navigates through a series of perilous levels to rescue the Princess.",
                    'score' => 8.0,
                    'genre' => "Action-adventure, platformer",
                    'publisher' => "Brøderbund",
                    'release_date' => "1989-10-03",
                ],
                [
                    'id' => 11,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/04/01/xwing-1648856399676.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Star Wars: X-Wing",
                    'description' => "A space simulation game in which the player pilots an X-wing starfighter for the Rebel Alliance, engaging in dogfights and completing various missions.",
                    'score' => 9.0,
                    'genre' => "Space simulation",
                    'publisher' => "LucasArts",
                    'release_date' => "1993-01-01",
                ],
                [
                    'id' => 12,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/09/monkeyisland2-1639016626307.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Monkey Island 2: LeChuck's Revenge",
                    'description' => "An adventure game in which the player controls Guybrush Threepwood, a pirate in search of the legendary treasure of Big Whoop, while also dealing with the ghost pirate LeChuck.",
                    'score' => 9.5,
                    'genre' => "Adventure",
                    'publisher' => "LucasArts",
                    'release_date' => "19911-12-01",
                ],
                [
                    'id' => 13,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/30/ultima7-1648674172163.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Ultima VII: The Black Gate",
                    'description' => "A role-playing game in which the player takes on the role of the Avatar, a hero on a quest to stop a cult from summoning a powerful demon.",
                    'score' => 8.5,
                    'genre' => "Role-playing",
                    'publisher' => "Origin Systems",
                    'release_date' => "1992-04-16",
                ],
                [
                    'id' => 14,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/diablo1-sq-1643999156851.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Diablo",
                    'description' => "An action role-playing game in which the player must explore a dungeon beneath the town of Tristram, battling various monsters and the demon Diablo himself.",
                    'score' => 9.0,
                    'genre' => "Action role-playing",
                    'publisher' => "Blizzard Entertainment",
                    'release_date' => "1996-12-31",
                ],
                [
                    'id' => 15,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/13/daggerfall-es-sq-1642032706144.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "The Elder Scrolls II: Daggerfall",
                    'description' => "A role-playing game in which the player explores a vast open world, completing quests and battling monsters to uncover the truth behind a sinister conspiracy.",
                    'score' => 8.0,
                    'genre' => "Role-playing",
                    'publisher' => "Bethesda Softworks",
                    'release_date' => "1996-08-31",
                ],
                [
                    'id' => 16,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/syndicate-sq-1644001563752.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Syndicate",
                    'description' => "A real-time tactics game in which the player controls a team of cyborg agents, completing missions and battling rival syndicates in a dystopian future.",
                    'score' => 8.5,
                    'genre' => "RTS",
                    'publisher' => "Bullfrog Productions",
                    'release_date' => "1993-06-06",
                ],
                [
                    'id' => 17,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/aloneinthedark-sq2-1644001153398.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Alone in the Dark",
                    'description' => "A survival horror game in which the player must solve puzzles and fight off supernatural enemies to escape a haunted mansion.",
                    'score' => 7.9,
                    'genre' => "Survival horror",
                    'publisher' => "Infogrames",
                    'release_date' => "1992-06-01",
                ],
                [
                    'id' => 18,
                    'game_image' => "https://cdn.cdkeys.com/700x700/media/catalog/product/f/1/f117a_nighthawk_stealth_fighter_2.0_pc.jpg",
                    'name' => "F-117A Nighthawk Stealth Fighter 2.0",
                    'description' => "A combat flight simulation game in which the player pilots the F-117A Nighthawk stealth fighter and engages in various missions.",
                    'score' => 7.2,
                    'genre' => "Flight simulation",
                    'publisher' => "MicroProse",
                    'release_date' => "1991-12-31",
                ],
                [
                    'id' => 19,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/24/wolfenstein-3d-button-1643068723102.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Wolfenstein 3D",
                    'description' => "A first-person shooter game in which the player must escape from a Nazi prison and defeat the evil regime.",
                    'score' => 8.3,
                    'genre' => "FPS",
                    'publisher' => "id Software",
                    'release_date' => "1992-05-05",
                ],
                [
                    'id' => 20,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/12/21/loungelizards-1671607111772.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Leisure Suit Larry 1: In the Land of the Lounge Lizards",
                    'description' => "A comedic adventure game in which the player must help the protagonist Larry Laffer find love and navigate the seedy underbelly of the city.",
                    'score' => 6.7,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1987-05-05",
                ],
                [
                    'id' => 21,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/14/myst-1652553321305.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Myst",
                    'description' => "An adventure game in which the player explores a mysterious island, solving puzzles and uncovering the secrets of the island's past.",
                    'score' => 9.0,
                    'genre' => "Adventure",
                    'publisher' => "Broderbund",
                    'release_date' => "1993-09-24",
                ],
                [
                    'id' => 22,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/30/uunderworlds-1648680562969.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Ultima Underworld: The Stygian Abyss",
                    'description' => "A first-person action RPG game in which the player explores the Stygian Abyss, battling foes and completing quests to save the world from destruction.",
                    'score' => 8.5,
                    'genre' => "RPG",
                    'publisher' => "Origin Systems",
                    'release_date' => "1992-03-23",
                ],
                [
                    'id' => 22,
                    'game_image' => "https://miabandonaware.com/wp-content/uploads/2017/11/BattleChess.jpg",
                    'name' => "Battle Chess",
                    'description' => "A chess game in which the pieces come to life and battle it out on the board in animated sequences.",
                    'score' => 7.5,
                    'genre' => "Board game",
                    'publisher' => "Interplay Productions",
                    'release_date' => "1988-12-31",
                ],
                [
                    'id' => 23,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/12/sidmeiersciv-sq-1641950900839.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Civilization",
                    'description' => "A strategy game in which the player guides a civilization from ancient times to the modern era, managing resources, building infrastructure, and waging war against other civilizations.",
                    'score' => 9.5,
                    'genre' => "Strategy",
                    'publisher' => "MicroProse",
                    'release_date' => "1991-09-01",
                ],
                [
                    'id' => 24,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/17/commanderkeen-sq-1645060606759.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Commander Keen",
                    'description' => "A platformer game in which the player controls a young boy named Billy Blaze who travels to alien planets to stop an evil alien race from destroying Earth.",
                    'score' => 8.5,
                    'genre' => "Platformer",
                    'publisher' => "id Software",
                    'release_date' => "1990-12-14",
                ],
                [
                    'id' => 25,
                    'game_image' => "https://pcmedia.ign.com/pc/image/object/006/006765/688985boxart_160w.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Quest for Glory: So You Want to Be a Hero",
                    'description' => "A hybrid adventure and RPG game in which the player creates a character and embarks on a quest to become a hero, completing quests and battling monsters along the way.",
                    'score' => 8.9,
                    'genre' => "Adventure/RPG",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1989-10-01",
                ],
                [
                    'id' => 26,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/systemshock-sq4-1644000955813.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "System Shock",
                    'description' => "A first-person action RPG game in which the player explores a space station and battles rogue AI and mutants to uncover the truth behind a sinister conspiracy.",
                    'score' => 9.0,
                    'genre' => "RPG",
                    'publisher' => "Looking Glass Technologies",
                    'release_date' => "1994-09-22",
                ],
                [
                    'id' => 27,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/03/24/simant-1679696128032.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "SimAnt",
                    'description' => "A simulation game in which the player controls an ant colony, managing resources, battling other insects, and expanding the colony's territory.",
                    'score' => 7.8,
                    'genre' => "Simulation",
                    'publisher' => "Maxis",
                    'release_date' => "1991-12-31",
                ],
                [
                    'id' => 28,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/09/larry3-1652056361433.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Leisure Suit Larry 3: Passionate Patti in Pursuit of the Pulsating Pectorals",
                    'description' => "A comedic adventure game in which the player takes on the role of Patti, a friend of Larry's, who is on a quest to find a missing rock star and uncover a sinister plot.",
                    'score' => 7.1,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1989-11-01",
                ],
                [
                    'id' => 29,
                    'game_image' => "https://pcmedia.ign.com/pc/image/object/008/008649/StarControl2_PCBOX.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Star Control II",
                    'description' => "A space exploration and combat game in which the player commands a spaceship and travels the galaxy, interacting with alien races, gathering resources, and battling enemy ships.",
                    'score' => 9.3,
                    'genre' => "Action/Strategy",
                    'publisher' => "Accolade",
                    'release_date' => "1992-11-30",
                ],
                [
                    'id' => 30,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/indyfateofatlantis-sq-1644002663775.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Indiana Jones and the Fate of Atlantis",
                    'description' => "An adventure game in which the player controls Indiana Jones and sets out to find the lost city of Atlantis, using archaeological skills and combat tactics to overcome obstacles.",
                    'score' => 8.8,
                    'genre' => "Adventure",
                    'publisher' => "LucasArts",
                    'release_date' => "1992-06-01",
                ],
                [
                    'id' => 31,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/01/28/wingcommander-1674935838935.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Wing Commander",
                    'description' => "A space combat simulation game in which the player commands a spacecraft and battles enemy ships, advancing through a storyline and earning upgrades and promotions.",
                    'score' => 8.4,
                    'genre' => "Action/Simulation",
                    'publisher' => "Origin Systems",
                    'release_date' => "1990-09-26",
                ],
                [
                    'id' => 34,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/01/08/heroesmm-1673204904360.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Heroes of Might and Magic",
                    'description' => "A turn-based strategy game in which the player builds and manages a kingdom, recruiting heroes, exploring the land, and engaging in battles against other factions.",
                    'score' => 8.8,
                    'genre' => "Strategy",
                    'publisher' => "New World Computing",
                    'release_date' => "1995-04-01",
                ],
                [
                    'id' => 35,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/04/02/lsl6-1680460509185.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Leisure Suit Larry 6: Shape Up or Slip Out!",
                    'description' => "A comedic adventure game in which the player controls Larry Laffer as he attempts to win a vacation to a luxury health spa, encountering humorous situations and romantic encounters along the way.",
                    'score' => 7.6,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1993-12-31",
                ],
                [
                    'id' => 39,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/28/warcraft-1648495554534.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Warcraft: Orcs & Humans",
                    'description' => "A real-time strategy game in which the player builds and manages a kingdom, recruiting units, gathering resources, and engaging in battles against enemy factions.",
                    'score' => 8.8,
                    'genre' => "Strategy",
                    'publisher' => "Blizzard Entertainment",
                    'release_date' => "1994-11-23",
                ],
                [
                    'id' => 40,
                    'game_image' => "https://assets1.ignimgs.com/2014/04/05/gabrielknight-o-r-i-g-i-n-a-l-original-menujpg-0a5e35.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Gabriel Knight: Sins of the Fathers",
                    'description' => "A point-and-click adventure game in which the player takes on the role of Gabriel Knight, a struggling writer and bookstore owner who becomes embroiled in a series of murders connected to voodoo rituals in New Orleans.",
                    'score' => 8.7,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1993-12-17",
                ],
                [
                    'id' => 41,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/13/policequest1-1652481063312.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Police Quest: In Pursuit of the Death Angel",
                    'description' => "A police procedural adventure game in which the player takes on the role of Sonny Bonds, a police officer in the fictional city of Lytton, as he investigates a string of drug-related crimes.",
                    'score' => 7.5,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1987-12-10",
                ],
                [
                    'id' => 42,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/14/lemmings-sq1-1644881071704.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Lemmings",
                    'description' => "A puzzle game in which the player guides a group of lemmings through increasingly difficult levels by assigning them tasks and abilities to avoid obstacles and reach the exit.",
                    'score' => 8.4,
                    'genre' => "Puzzle",
                    'publisher' => "Psygnosis",
                    'release_date' => "1991-02-14",
                ],
                [
                    'id' => 43,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/01/14/railroadtycoon-1673728170649.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Railroad Tycoon",
                    'description' => "A business simulation game in which the player manages a railroad company, laying tracks, managing resources, and competing against rival companies to become the dominant force in the industry.",
                    'score' => 8.3,
                    'genre' => "Simulation",
                    'publisher' => "MicroProse",
                    'release_date' => "1990-10-15",
                ],
                [
                    'id' => 44,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/13/street-fighter-2-button-snescrop-1652485158101.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Street Fighter 2",
                    'description' => "This classic fighting game was released in 1992 and is considered one of the greatest games of all time.",
                    'score' => 9.2,
                    'genre' => "Fighting",
                    'publisher' => "Capcom",
                    'release_date' => "1992-02-06",
                ],
                [
                    'id' => 45,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/12/17/chipschallenge-1671293451816.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Chip's Challenge",
                    'description' => "This puzzle game was released in 1991 and challenges players to solve increasingly difficult levels.",
                    'score' => 7.5,
                    'genre' => "Puzzle",
                    'publisher' => "Epyx",
                    'release_date' => "1991-11-01",
                ],
                [
                    'id' => 46,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/30/ultima7-1648674172163.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Ultima 7 Part 1: The Black Gate",
                    'description' => "This classic RPG was released in 1992 and is considered one of the greatest games of all time.",
                    'score' => 9.1,
                    'genre' => "RPG",
                    'publisher' => "Origin Systems",
                    'release_date' => "1992-04-16",
                ],
                [
                    'id' => 47,
                    'game_image' => "https://upload.wikimedia.org/wikipedia/en/f/fc/ARC_Cisco_Heat_%28Cisco_Heat_-_All_American_Police_Car_Race%29.png",
                    'name' => "Cisco Heat",
                    'description' => "This racing game was released in 1991 and challenges players to compete in high-speed races.",
                    'score' => 6.9,
                    'genre' => "Racing",
                    'publisher' => "Jaleco",
                    'release_date' => "1991-12-31",
                ],
                [
                    'id' => 48,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/08/18/test-drive-the-duel-object-1660790617166.png?width=300&crop=1%3A1%2Csmart",
                    'name' => "The Duel: Test Drive 2",
                    'description' => "This racing game was released in 1989 and challenges players to compete in high-speed races.",
                    'score' => 8.0,
                    'genre' => "Racing",
                    'publisher' => "Accolade",
                    'release_date' => "1989-10-31",
                ],
                [
                    'id' => 49,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/01/22/transporttdx-1674429941083.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Transport Tycoon Deluxe",
                    'description' => "This business simulation game was released in 1995 and challenges players to build and manage a transportation network.",
                    'score' => 8.9,
                    'genre' => "Simulation",
                    'publisher' => "MicroProse",
                    'release_date' => "1995-04-14",
                ],
                [
                    'id' => 50,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/14/operationwolf-1647221682862.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Operation Wolf",
                    'description' => "This classic shooter game was released in 1989 and challenges players to fight their way through enemy lines.",
                    'score' => 7.6,
                    'genre' => "Shooter",
                    'publisher' => "Taito",
                    'release_date' => "1989-07-01",
                ],
                [
                    'id' => 51,
                    'game_image' => "https://pcmedia.ign.com/pc/image/object/003/003121/683616boxart_160h.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Outcast",
                    'description' => "This action-adventure game was released in 1999 and challenges players to explore an alien world.",
                    'score' => 8.7,
                    'genre' => "Action-Adventure",
                    'publisher' => "Infogrames",
                    'release_date' => "1999-06-30",
                ],
                [
                    'id' => 52,
                    'game_image' => "https://media.gamestats.com/gg/image/object/007/007836/SidMeierscolonization_PCBOX.jpg",
                    'name' => "Colonization",
                    'description' => "This strategy game was released in 1994 and challenges players to establish and manage a colony in the New World.",
                    'score' => 8.5,
                    'genre' => "Strategy",
                    'publisher' => "MicroProse",
                    'release_date' => "1994-09-01",
                ],
                [
                    'id' => 54,
                    'game_image' => "https://pcmedia.ign.com/pc/image/object/855/855242/689007boxart_160w.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Wizardry 7: Crusaders of the Dark Savant",
                    'description' => "This role-playing game was released in 1992 and challenges players to explore a vast world while battling monsters and solving puzzles.",
                    'score' => 9.0,
                    'genre' => "RPG",
                    'publisher' => "Sir-Tech",
                    'release_date' => "1992-11-14",
                ],
                [
                    'id' => 55,
                    'game_image' => "Duke Nukem",
                    'name' => "Duke Nukem",
                    'description' => "This side-scrolling shooter game was released in 1991 and challenges players to save the world from an alien invasion.",
                    'score' => 8.0,
                    'genre' => "Shooter",
                    'publisher' => "Apogee Software",
                    'release_date' => "1991-07-01",
                ],
                [
                    'id' => 56,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/03/11/whiplash-1678564114930.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Whiplash",
                    'description' => "This racing game was released in 1995 and challenges players to race through dangerous courses and destroy their opponents.",
                    'score' => 6.9,
                    'genre' => "Racing",
                    'publisher' => "Interplay",
                    'release_date' => "1995-08-31",
                ],
                [
                    'id' => 57,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/04/09/battlezone-1649519688612.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => 'Battlezone',
                    'description' => 'This first-person tank combat game was released in 1983 and challenges players to defeat enemy tanks and UFOs while capturing bases.',
                    'score' => 7.5,
                    'genre' => 'Action',
                    'publisher' => 'Atari, Inc.',
                    'release_date' => '1983-11-30'
                ],
                [
                    'id' => 58,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/02/hereticexpansion-sq-1643825958468.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => 'Heretic',
                    'description' => 'This first-person shooter game was released in 1994 and challenges players to fight off hordes of demons in a fantasy world.',
                    'score' => 8.3,
                    'genre' => 'Shooter',
                    'publisher' => 'id Software',
                    'release_date' => '1994-12-23'
                ],
                [
                    'id' => 59,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/07/25/alleycat-1658776590870.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => 'Alley Cat',
                    'description' => 'This action game was released in 1984 and challenges players to navigate a cat through obstacles to catch mice and avoid dogs.',
                    'score' => 6.8,
                    'genre' => 'Action',
                    'publisher' => 'IBM',
                    'release_date' => '1984-12-31'
                ],
                [
                    'id' => 60,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/30/roadrashps-1648601093749.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => 'Road Rash',
                    'description' => 'This motorcycle racing game was released in 1996 and challenges players to race through traffic and take down opponents with weapons.',
                    'score' => 8.7,
                    'genre' => 'Racing',
                    'publisher' => 'Electronic Arts, Inc.',
                    'release_date' => '1996-09-30'
                ],
                [
                    'id' => 61,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/19/futureshock-sq-1645235967876.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => 'The Terminator: Future Shock',
                    'description' => 'This first-person shooter game was released in 1995 and challenges players to fight off Skynet and its robots in a post-apocalyptic future.',
                    'score' => 8.1,
                    'genre' => 'Shooter',
                    'publisher' => 'Bethesda Softworks LLC',
                    'release_date' => '1995-12-05'
                ],
                [
                    'id' => 62,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/12/30/pipedream-1672422764301.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Pipe Dream",
                    'description' => "This puzzle game was released in 1989 and challenges players to build a pipeline to transport a green ooze from one side of the screen to the other.",
                    'score' => 7.5,
                    'genre' => "Puzzle",
                    'publisher' => "LucasArts",
                    'release_date' => "1989-01-01",
                ],
                [
                    'id' => 63,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/10/05/loom-1664996250692.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Loom",
                    'description' => "This adventure game was released in 1990 and follows the journey of Bobbin Threadbare, a young weaver who has the ability to spin magical threads.",
                    'score' => 8.0,
                    'genre' => "Adventure",
                    'publisher' => "Lucasfilm Games",
                    'release_date' => "1990-01-01",
                ],
                [
                    'id' => 64,
                    'game_image' => "https://media.ign.com/games/image/object/065/065279/Mahjong-Solitaire_dl10_PS_Minis.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Mah Jongg Solitaire",
                    'description' => "This puzzle game was released in 1987 and is a solitaire version of the popular tile-based game Mahjong.",
                    'score' => 6.9,
                    'genre' => "Puzzle",
                    'publisher' => "Broderbund",
                    'release_date' => "1987-01-01",
                ],
                [
                    'id' => 65,
                    'game_image' => "https://macmedia.ign.com/mac/image/object/490/490721/612220.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Links 386 Pro",
                    'description' => "This sports game was released in 1992 and is a golf simulator that allows players to customize their own golf courses and compete against other players.",
                    'score' => 7.6,
                    'genre' => "Sports",
                    'publisher' => "Access Software",
                    'release_date' => "1992-01-01",
                ],
                [
                    'id' => 66,
                    'game_image' => "https://pcmedia.ign.com/pc/image/ironblitzallies_pcbox.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Axis and Allies: Iron Blitz",
                    'description' => "A turn-based strategy game based on the board game of the same name, set during World War II.",
                    'score' => 7.5,
                    'genre' => "Strategy",
                    'publisher' => "Hasbro Interactive",
                    'release_date' => "1999-06-30",
                ],
                [
                    'id' => 67,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/01/26/phantasmagoria-1674716912119.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Phantasmagoria",
                    'description' => "A horror adventure game, following the story of a writer and his wife as they move into a haunted mansion.",
                    'score' => 8.2,
                    'genre' => "Adventure",
                    'publisher' => "Sierra On-Line",
                    'release_date' => "1995-08-24",
                ],
                [
                    'id' => 68,
                    'game_image' => "https://www.myabandonware.com/media/screenshots/g/gloriana-j3a/gloriana_2.jpg",
                    'name' => "Gloriana",
                    'description' => "A side-scrolling platformer, in which the player takes on the role of the queen of a kingdom fighting against a group of usurpers.",
                    'score' => 6.8,
                    'genre' => "Platformer",
                    'publisher' => "Broderbund Software",
                    'release_date' => "1996-01-01",
                ],
                [
                    'id' => 69,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/05/13/midtownmadness-1652466735122.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Midtown Madness",
                    'description' => "A racing game set in Chicago, featuring a variety of vehicles and game modes.",
                    'score' => 7.8,
                    'genre' => "Racing",
                    'publisher' => "Microsoft Game Studios",
                    'release_date' => "1999-02-27",
                ],
                [
                    'id' => 70,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/26/oregontrail-1648323175357.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "The Oregon Trail Deluxe",
                    'description' => "An educational game simulating a journey along the Oregon Trail during the 19th century.",
                    'score' => 7.4,
                    'genre' => "Simulation",
                    'publisher' => "MECC",
                    'release_date' => "1992-01-01",
                ],
                [
                    'id' => 71,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/07/mk-1992-1638899209756.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Mortal Kombat",
                    'description' => "A fighting game featuring a cast of characters with unique moves and fatalities.",
                    'score' => 8.6,
                    'genre' => "Fighting",
                    'publisher' => "Midway Games",
                    'release_date' => "1992-10-08",
                ],
                [
                    'id' => 72,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/03/23/diggerhd-1648078168391.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Diggers",
                    'description' => "This puzzle game was released in 1994 and challenges players to dig through dirt to find valuable gems.",
                    'score' => 7.8,
                    'genre' => "Puzzle",
                    'publisher' => "Millennium Interactive",
                    'release_date' => "1994-12-31",
                ],
                [
                    'id' => 73,
                    'game_image' => "https://assets-prd.ignimgs.com/2021/12/29/age-of-empires-2-age-pf-kings-button-1640820759986.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Age of Empires 2: The Age of Kings",
                    'description' => "This real-time strategy game was released in 1999 and challenges players to build an empire and conquer their enemies.",
                    'score' => 9.5,
                    'genre' => "Strategy",
                    'publisher' => "Microsoft",
                    'release_date' => "1999-09-30",
                ],
                [
                    'id' => 74,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/12/civilization2-sq-1641949315751.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Civilization 2",
                    'description' => "This turn-based strategy game was released in 1996 and challenges players to build a civilization from scratch and lead it to greatness.",
                    'score' => 9.2,
                    'genre' => "Strategy",
                    'publisher' => "MicroProse",
                    'release_date' => "1996-02-29",
                ],
                [
                    'id' => 75,
                    'game_image' => "https://pcmedia.ign.com/pc/image/object/013/013853/612284boxart_160w.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Dogs of War",
                    'description' => "This turn-based strategy game was released in 1996 and challenges players to lead a mercenary army and complete various missions.",
                    'score' => 7.6,
                    'genre' => "Strategy",
                    'publisher' => "GTE Entertainment",
                    'release_date' => "1996-10-31",
                ],
                [
                    'id' => 76,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/01/25/junglestrikesequel-sq-1643143378948.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Jungle Strike",
                    'description' => "This action game was released in 1995 and challenges players to complete various missions in a helicopter.",
                    'score' => 8.4,
                    'genre' => "Action",
                    'publisher' => "Electronic Arts",
                    'release_date' => "1995-06-30",
                ],
                [
                    'id' => 77,
                    'game_image' => "https://t.gamesnostalgia.com/screenshots/u/g/ugh/38417.jpg",
                    'name' => "Ugh!",
                    'description' => "In this side-scrolling action game, players control a prehistoric man riding a pterodactyl, with the goal of collecting as many treasures as possible while avoiding obstacles and enemies.",
                    'score' => 7.5,
                    'genre' => "Action",
                    'publisher' => "Play Byte",
                    'release_date' => "1992-01-01",
                ],
                [
                    'id' => 78,
                    'game_image' => "https://assets-prd.ignimgs.com/2022/02/04/desertstrike-sq-1644002247355.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Desert Strike: Return to the Gulf",
                    'description' => "In this helicopter-based shoot 'em up, players control a member of the U.S. military tasked with taking down a Middle Eastern dictator.",
                    'score' => 8.3,
                    'genre' => "Action",
                    'publisher' => "Electronic Arts",
                    'release_date' => "1994-02-01",
                ],
                [
                    'id' => 79,
                    'game_image' => "https://codesmedia.ign.com/codes/image/object/000/000114/614185.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "Panzer General",
                    'description' => "There is a Game in There",
                    'score' => 2.5,
                    'genre' => "Strategy",
                    'publisher' => "Mindscape",
                    'release_date' => "1994-12-01",
                ],
                [
                    'id' => 80,
                    'game_image' => "https://assets-prd.ignimgs.com/2023/02/13/midtownmadness2-1676322357793.jpg?width=300&crop=1%3A1%2Csmart",
                    'name' => "MIDTOWN MADNESS 2",
                    'description' => "Run fast like the wind.",
                    'score' => 10,
                    'genre' => "Racing",
                    'publisher' => "Empire Interactive Europe Ltd",
                    'release_date' => "2000-09-22",
                ],
            ]
        );
    }
}
